name: Feature suggestion
description: Suggest a new feature
type: Feature
labels: ["S-Triage"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to suggest a feature!
  - type: textarea
    id: describe
    attributes:
      label: Describe the feature
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Suggestion or example of how the feature would be used
  - type: checkboxes
    id: duplicate
    attributes:
      label: Duplicate declaration
      options:
        - label: I have searched the issues and this feature has not been requested before.
          required: true
