name: Improvement suggestion
description: Suggest an improvement to an existing feature
type: Improvement
labels: ["S-Triage"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to suggest an improvement!
  - type: textarea
    id: describe
    attributes:
      label: Describe the improvement
    validations:
      required: true
  - type: checkboxes
    id: duplicate
    attributes:
      label: Duplicate declaration
      options:
        - label: I have searched the issues and this improvement has not been requested before.
          required: true
