FROM rust:buster as runtime
RUN apt-get update &&\
    apt-get install -y curl postgresql supervisor
RUN pg_dropcluster $(pg_lsclusters -h | cut -d' ' -f-2 | head -n1)
RUN rustup component add rust-src

FROM rust:buster AS builder
RUN apt-get update &&\
    apt-get install -y protobuf-compiler
WORKDIR app
COPY . .
RUN cargo build --bin provisioner -p provisioner

FROM runtime
WORKDIR /
COPY --from=builder /app/target/debug/provisioner /usr/local/bin/shuttle-provisioner

COPY provisioner/docker/entrypoint.sh /bin/entrypoint.sh
COPY provisioner/docker/wait-for-pg-then /usr/bin/wait-for-pg-then
COPY provisioner/docker/supervisord.conf /usr/share/supervisord/supervisord.conf
ENTRYPOINT ["/bin/entrypoint.sh"]
