FROM rust:buster as runtime
RUN apt-get update &&\
    apt-get install -y supervisor
RUN rustup component add rust-src

FROM rust:buster AS builder
RUN apt-get update &&\
    apt-get install -y protobuf-compiler
WORKDIR app
COPY . .
COPY ./api/docker/config.toml $CARGO_HOME/config.toml
RUN cargo build --bin api -p api

FROM runtime
WORKDIR /
COPY --from=builder /app/target/debug/api /usr/local/bin/shuttle-backend
COPY --from=builder /app/service /app/service
COPY --from=builder /app/common /app/common
COPY --from=builder /app/codegen /app/codegen

COPY api/docker/config.toml $CARGO_HOME/config.toml
COPY api/docker/entrypoint.sh /bin/entrypoint.sh
COPY api/docker/supervisord.conf /usr/share/supervisord/supervisord.conf
ENTRYPOINT ["/bin/entrypoint.sh"]

HEALTHCHECK --interval=5s --timeout=5s CMD curl --fail http://localhost:8001/status || exit 1
